PATH:
  INPUT: "./raw_txt_input"
  OUTPUT: "./output"
  DEFAULT_EXPERIENCES: "./experiences"  # Add this line to specify the default directory for experience YAML files
  EXPERIENCES: "./experiences"
API:
  NVIDIA_API_KEY: "nvapi-ADdapdo323-098daa13adpdi1p34" #no this isn't my API key, don't try it
  NVIDIA_BASE_URL: "https://integrate.api.nvidia.com/v1"
  NVIDIA_MODEL: "nvidia/nemotron-4-340b-instruct"
SYSTEM:
  DOUBLE_CHECK_COUNT: 3
  USE_SUBSET: True
  CONCURRENCY_LIMIT: 10
  COMPLETION_MODE: False
  MODE: "api"
REQUIREMENTS:
  GUIDELINES:
    - "Take your time and analyze each step of the problem before answering."
    - "Highlight each step involved in answering the question."
    - "Only answer the question once you've described each step of the thought process involved in your answer."
  OBJECTIVES:
    - "Utilize the provided data to generate a completely different interaction."
    - "Rewrite the provided data to highlight each individual step or thought process used to come to the following conclusion."
  AVOID:
    - "Do not answer the question until each step has been carefully laid out."
    - "Do not just write the same question and answer. Generate a new questino and answer from the provided data."
    - "Do not phrase the question as if it were a multiple choice answer. Instead, write a new question that deals with the same topic discussed in the following example."
  META_INSTRUCTIONS:
    - "Show the work that you did in order to answer the question."
  MUTATORS: []  # Remove the mutators as they are not needed for this specific task
  OVERALL_TASK_DESC: "Generate in-depth, thoughtful interactions between a human and an artificial intelligence by analyzing each step of the thought process before answering the question, based on provided data."
  TASKS: []  # Remove the tasks as they are not needed for this specific task
